version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL:-http://localhost:8080}
      # RoadRunner
      - RR_MODE=http
      - RR_RPC_ENABLED=true
      - RR_DEBUG=${APP_DEBUG:-false}
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
